// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateResourceInput struct {
	SubjectID   string  `json:"subjectId"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	FileURL     string  `json:"fileUrl"`
	FileSize    *int32  `json:"fileSize,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Resource struct {
	ID          string   `json:"id"`
	Title       string   `json:"title"`
	Description *string  `json:"description,omitempty"`
	FileURL     string   `json:"fileUrl"`
	FileSize    *int32   `json:"fileSize,omitempty"`
	CreatedAt   string   `json:"createdAt"`
	Owner       *User    `json:"owner"`
	Subject     *Subject `json:"subject"`
}

type Study struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	Subjects []*Subject `json:"subjects"`
}

type Subject struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Year      *string     `json:"year,omitempty"`
	Resources []*Resource `json:"resources"`
}

type User struct {
	ID        string      `json:"id"`
	Email     string      `json:"email"`
	FullName  *string     `json:"fullName,omitempty"`
	Pfp       *string     `json:"pfp,omitempty"`
	Study     *Study      `json:"study,omitempty"`
	Resources []*Resource `json:"resources"`
}
