package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/DCCXXV/Nemsy/backend/internal/graph/model"
)

// UpdateMyStudy is the resolver for the updateMyStudy field.
func (r *mutationResolver) UpdateMyStudy(ctx context.Context, studyID string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UpdateMyStudy - updateMyStudy"))
}

// CreateResource is the resolver for the createResource field.
func (r *mutationResolver) CreateResource(ctx context.Context, input model.CreateResourceInput) (*model.Resource, error) {
	panic(fmt.Errorf("not implemented: CreateResource - createResource"))
}

// DeleteResource is the resolver for the deleteResource field.
func (r *mutationResolver) DeleteResource(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteResource - deleteResource"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Studies is the resolver for the studies field.
func (r *queryResolver) Studies(ctx context.Context) ([]*model.Study, error) {
	panic(fmt.Errorf("not implemented: Studies - studies"))
}

// Subjects is the resolver for the subjects field.
func (r *queryResolver) Subjects(ctx context.Context, studyID string) ([]*model.Subject, error) {
	panic(fmt.Errorf("not implemented: Subjects - subjects"))
}

// Resources is the resolver for the resources field.
func (r *queryResolver) Resources(ctx context.Context, subjectID string) ([]*model.Resource, error) {
	panic(fmt.Errorf("not implemented: Resources - resources"))
}

// Resource is the resolver for the resource field.
func (r *queryResolver) Resource(ctx context.Context, id string) (*model.Resource, error) {
	panic(fmt.Errorf("not implemented: Resource - resource"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
